### ISSUE TITLE
[Feature request] Events

### ISSUE THREAD

**Issue by Fleeck** [crowdbotics/v-img#14]
Hi, i really need such events as `open` & `close` for gallery. Could you please add this? Thanks in advance.

**Comment by fahrenq** [comment]
Hey @Fleeck!
Thanks for feature suggestion. Can you please provide an example how you would like to see this functionality implemented on the end side?

**Comment by Fleeck** [comment]
@fahrenq 
I dont know much about emitting from directives, however it would be great to have `open/close` events emitted every time when gallery opens/closes.

**Comment by fahrenq** [comment]
I agree with you, it reveals much more space to art beautiful interfaces! So, since we have image gallery implemented with separate Vue instance stored in `window.vueImg`, we can try to emit and listen to events though this variable. I'm not sure in details for now. So, I'll implement it as soon as I have time, have a lot of work now.
Thanks!

**Comment by Fleeck** [comment]
Sounds like a plan. Looking forward to the update :)

**Comment by Fleeck** [comment]
@fahrenq hey, any updates on this?

**Comment by fahrenq** [comment]
Hey @Fleeck!
Don't have any updates yet, sorry. I'll ping you here for any updates or discussions.
Thanks!

**Comment by fahrenq** [comment]
#20 Progress

**Comment by fahrenq** [comment]
Added in v.0.1.1
a00c835932aaa0d0c14c17642c52cfc0efbf8cdf
Big thanks to @trueromanus for implementing core of this feature.
