### ISSUE TITLE
Possible to use together with progressive-img?

### ISSUE THREAD

**Issue by bobcat1** [crowdbotics/v-img#26]
My images are quite large, so I would like to load them progressively. So I found this https://github.com/MatteoGabriele/vue-progressive-image , but the problem is that it requires you change the `img` tag to `progressive-img`, thus breaks the `v-img`, giving an error saying: `v-img element missing src parameter.`

Is there any way to get this working?

Regards,

**Comment by fahrenq** [comment]
Hello!

Unfortunately, I didn't yet test plugin with custom components.
Probably the problem in [this line](https://github.com/crowdbotics/v-img/blob/master/lib/index.js#L9), because components don't behave as normal nodes.

As a dirty workaround, which is pretty dirty, I can advice you to use `src` directive option:
```vuejs
<progressive-img v-img="{ src: 'src-to-display-in-gallery' }" src="...">
```
But it still might not work. Need testing. I've created separate issue for this feature - #27, you will see updates and discussions there.

Thank you very much for feature suggestion!
If you don't mind I'll close this issue, feel free to open this or create new in case of any questions.
